import cleanMatchaGreen from "./image/clean matcha green.svg";
import cleanse from "./image/cleanse.svg";
import detox from "./image/detox.svg";

const products = [
  {
    id: 1,
    productName: "Phalada Pure & Sure | Organic Coconut Milk-160ml",
    description: "Organic coconut milk made from premium coconuts.",
    category: "Beverage",
    subCategory: "EXTRA VIRGIN OLIVE OIL",
    sku: "#PPS101",
    stockQuantity: 211,
    regularPrice: 1749,
    offerPrice: 1179,
    rating: 5,
    reviews: 286,
    thumbnail: cleanMatchaGreen,
    tags: ["Lorem", "Lorem"],
    isSale: true,
    status: "active",
  },

  {
    id: 2,
    productName: "Woodi Peck's Araku Organic Black Coffee Powder – 250 Grams",
    description: "Premium organic black coffee from Araku Valley.",
    category: "Coffee",
    subCategory: "COFFEE",
    sku: "#COF101",
    stockQuantity: 180,
    regularPrice: 1749,
    offerPrice: 1179,
    rating: 5,
    reviews: 286,
    thumbnail: cleanse,
    tags: ["Coffee", "Organic"],
    isSale: true,
    status: "active",
  },

  {
    id: 3,
    productName: "Nutriboat Okra Chips – Spiced & Stormy",
    description: "Healthy and crunchy okra chips.",
    category: "SWEETS & SNACKS",
    subCategory: "SWEETS & SAVOURIES",
    sku: "#SNK101",
    stockQuantity: 95,
    regularPrice: 899,
    offerPrice: 699,
    rating: 4,
    reviews: 215,
    thumbnail: detox,
    tags: ["Snacks", "Healthy"],
    isSale: false,
    status: "active",
  },
  {
    id: 4,
    productName: "Phalada Pure & Sure | Organic Coconut Milk-160ml",
    description: "Organic coconut milk made from premium coconuts.",
    category: "Beverage",
    subCategory: "EXTRA VIRGIN OLIVE OIL",
    sku: "#PPS101",
    stockQuantity: 211,
    regularPrice: 1749,
    offerPrice: 1179,
    rating: 5,
    reviews: 286,
    thumbnail: cleanMatchaGreen,
    tags: ["Organic", "Healthy"],
    isSale: true,
    status: "active",
  },

  {
    id: 5,
    productName: "Woodi Peck's Araku Organic Black Coffee Powder – 250 Grams",
    description: "Premium organic black coffee from Araku Valley.",
    category: "Coffee",
    subCategory: "COFFEE",
    sku: "#COF101",
    stockQuantity: 180,
    regularPrice: 1749,
    offerPrice: 1179,
    rating: 5,
    reviews: 286,
    thumbnail: cleanse,
    tags: ["Coffee", "Organic"],
    isSale: true,
    status: "active",
  },

  {
    id: 6,
    productName: "Nutriboat Okra Chips – Spiced & Stormy",
    description: "Healthy and crunchy okra chips.",
    category: "SWEETS & SNACKS",
    subCategory: "SWEETS & SAVOURIES",
    sku: "#SNK101",
    stockQuantity: 95,
    regularPrice: 899,
    offerPrice: 699,
    rating: 4,
    reviews: 215,
    thumbnail: detox,
    tags: ["Snacks", "Healthy"],
    isSale: false,
    status: "active",
  },
  {
    id: 7,
    productName: "Phalada Pure & Sure | Organic Coconut Milk-160ml",
    description: "Organic coconut milk made from premium coconuts.",
    category: "Beverage",
    subCategory: "EXTRA VIRGIN OLIVE OIL",
    sku: "#PPS101",
    stockQuantity: 211,
    regularPrice: 1749,
    offerPrice: 1179,
    rating: 5,
    reviews: 286,
    thumbnail: cleanMatchaGreen,
    tags: ["Organic", "Healthy"],
    isSale: true,
    status: "active",
  },

  {
    id: 8,
    productName: "Woodi Peck's Araku Organic Black Coffee Powder – 250 Grams",
    description: "Premium organic black coffee from Araku Valley.",
    category: "Coffee",
    subCategory: "COFFEE",
    sku: "#COF101",
    stockQuantity: 180,
    regularPrice: 1749,
    offerPrice: 1179,
    rating: 5,
    reviews: 286,
    thumbnail: cleanse,
    tags: ["Coffee", "Organic"],
    isSale: true,
    status: "active",
  },

  {
    id: 9,
    productName: "Nutriboat Okra Chips – Spiced & Stormy",
    description: "Healthy and crunchy okra chips.",
    category: "SWEETS & SNACKS",
    subCategory: "SWEETS & SNACKS",
    sku: "#SNK101",
    stockQuantity: 95,
    regularPrice: 899,
    offerPrice: 699,
    rating: 4,
    reviews: 215,
    thumbnail: detox,
    tags: ["Snacks", "Healthy"],
    isSale: false,
    status: "active",
  },
  {
    id: 10,
    productName: "Phalada Pure & Sure | Organic Coconut Milk-160ml",
    description: "Organic coconut milk made from premium coconuts.",
    category: "Beverage",
    subCategory: "EXTRA VIRGIN OLIVE OIL",
    sku: "#PPS101",
    stockQuantity: 211,
    regularPrice: 1749,
    offerPrice: 1179,
    rating: 5,
    reviews: 286,
    thumbnail: cleanMatchaGreen,
    tags: ["Organic", "Healthy"],
    isSale: true,
    status: "active",
  },

  {
    id: 11,
    productName: "Woodi Peck's Araku Organic Black Coffee Powder – 250 Grams",
    description: "Premium organic black coffee from Araku Valley.",
    category: "Coffee",
    subCategory: "COFFEE",
    sku: "#COF101",
    stockQuantity: 180,
    regularPrice: 1749,
    offerPrice: 1179,
    rating: 5,
    reviews: 286,
    thumbnail: cleanse,
    tags: ["Coffee", "Organic"],
    isSale: true,
    status: "active",
  },

  {
    id: 12,
    productName: "Nutriboat Okra Chips – Spiced & Stormy",
    description: "Healthy and crunchy okra chips.",
    category: "SWEETS & SNACKS",
    subCategory: "SWEETS & SAVOURIES",
    sku: "#SNK101",
    stockQuantity: 95,
    regularPrice: 899,
    offerPrice: 699,
    rating: 4,
    reviews: 215,
    thumbnail: detox,
    tags: ["Snacks", "Healthy"],
    isSale: false,
    status: "active",
  },
];

export default products;
