const products = [
  {
    id: 1,
    productName: "Phalada Pure & Sure | Organic Coconut Milk-160ml",
    description: "Organic coconut milk made from premium coconuts.",
    category: "Beverage",
    subCategory: "Tea Product",
    sku: "#PPS101",
    stockQuantity: 211,
    regularPrice: 1749,
    offerPrice: 1179,
    rating: 5,
    reviews: 286,
    thumbnail: "/products/product-1.png",
    tags: ["Organic", "Healthy"],
    isSale: true,
    status: "active",
  },

  {
    id: 2,
    productName: "Woodi Peck's Araku Organic Black Coffee Powder – 250 Grams",
    description: "Premium organic black coffee from Araku Valley.",
    category: "Coffee",
    subCategory: "Coffee Product",
    sku: "#COF101",
    stockQuantity: 180,
    regularPrice: 1749,
    offerPrice: 1179,
    rating: 5,
    reviews: 286,
    thumbnail: "/products/product-2.png",
    tags: ["Coffee", "Organic"],
    isSale: true,
    status: "active",
  },

  {
    id: 3,
    productName: "Nutriboat Okra Chips – Spiced & Stormy",
    description: "Healthy and crunchy okra chips.",
    category: "Snacks",
    subCategory: "Savouries",
    sku: "#SNK101",
    stockQuantity: 95,
    regularPrice: 899,
    offerPrice: 699,
    rating: 4,
    reviews: 215,
    thumbnail: "/products/product-3.png",
    tags: ["Snacks", "Healthy"],
    isSale: false,
    status: "active",
  },

  {
    id: 4,
    productName: "Organic Green Tea Premium",
    description: "Refreshing green tea with antioxidants.",
    category: "Beverage",
    subCategory: "Tea Product",
    sku: "#TEA101",
    stockQuantity: 120,
    regularPrice: 999,
    offerPrice: 749,
    rating: 4,
    reviews: 190,
    thumbnail: "/products/product-4.png",
    tags: ["Tea", "Organic"],
    isSale: true,
    status: "active",
  },

  {
    id: 5,
    productName: "Natural Honey 500gm",
    description: "Pure and natural forest honey.",
    category: "Health & Wellness",
    subCategory: "Honey",
    sku: "#HON101",
    stockQuantity: 85,
    regularPrice: 799,
    offerPrice: 649,
    rating: 5,
    reviews: 320,
    thumbnail: "/products/product-5.png",
    tags: ["Honey", "Natural"],
    isSale: true,
    status: "active",
  },

  {
    id: 6,
    productName: "Cold Pressed Coconut Oil",
    description: "Virgin coconut oil extracted naturally.",
    category: "Extra Virgin Oils",
    subCategory: "Coconut Oil",
    sku: "#OIL101",
    stockQuantity: 150,
    regularPrice: 1199,
    offerPrice: 899,
    rating: 5,
    reviews: 250,
    thumbnail: "/products/product-6.png",
    tags: ["Oil", "Organic"],
    isSale: true,
    status: "active",
  },

  {
    id: 7,
    productName: "Organic Turmeric Powder",
    description: "Premium quality turmeric powder.",
    category: "Supplements",
    subCategory: "Spices",
    sku: "#SUP101",
    stockQuantity: 175,
    regularPrice: 499,
    offerPrice: 399,
    rating: 4,
    reviews: 140,
    thumbnail: "/products/product-7.png",
    tags: ["Turmeric", "Organic"],
    isSale: false,
    status: "active",
  },

  {
    id: 8,
    productName: "Herbal Detox Tea",
    description: "Herbal tea blend for detox and wellness.",
    category: "Beverage",
    subCategory: "Tea Product",
    sku: "#TEA102",
    stockQuantity: 90,
    regularPrice: 699,
    offerPrice: 549,
    rating: 4,
    reviews: 170,
    thumbnail: "/products/product-8.png",
    tags: ["Tea", "Detox"],
    isSale: true,
    status: "active",
  },

  {
    id: 9,
    productName: "Organic Almond Butter",
    description: "Creamy almond butter with no preservatives.",
    category: "Health & Wellness",
    subCategory: "Nut Butter",
    sku: "#ALM101",
    stockQuantity: 110,
    regularPrice: 899,
    offerPrice: 749,
    rating: 5,
    reviews: 210,
    thumbnail: "/products/product-9.png",
    tags: ["Almond", "Protein"],
    isSale: true,
    status: "active",
  },

  {
    id: 10,
    productName: "Premium Black Tea",
    description: "Rich and aromatic black tea leaves.",
    category: "Beverage",
    subCategory: "Tea Product",
    sku: "#TEA103",
    stockQuantity: 135,
    regularPrice: 599,
    offerPrice: 449,
    rating: 4,
    reviews: 180,
    thumbnail: "/products/product-10.png",
    tags: ["Tea", "Black Tea"],
    isSale: false,
    status: "active",
  },

  {
    id: 11,
    productName: "Organic Cashew Nuts",
    description: "Crunchy premium-grade cashew nuts.",
    category: "Snacks",
    subCategory: "Dry Fruits",
    sku: "#CAS101",
    stockQuantity: 125,
    regularPrice: 1399,
    offerPrice: 1099,
    rating: 5,
    reviews: 300,
    thumbnail: "/products/product-11.png",
    tags: ["Cashew", "Dry Fruits"],
    isSale: true,
    status: "active",
  },

  {
    id: 12,
    productName: "Extra Virgin Olive Oil 1L",
    description: "Cold-pressed extra virgin olive oil.",
    category: "Extra Virgin Oils",
    subCategory: "Olive Oil",
    sku: "#OLI101",
    stockQuantity: 70,
    regularPrice: 1999,
    offerPrice: 1599,
    rating: 5,
    reviews: 410,
    thumbnail: "/products/product-12.png",
    tags: ["Olive Oil", "Healthy"],
    isSale: true,
    status: "active",
  },
];

export default products;